name = "tg-channel-downloader"
main = "src/index.js"
compatibility_date = "2023-10-30"

# 环境变量配置
[vars]
# 这些值会被GitHub Actions中的环境变量覆盖
BOT_TOKEN = ""
ALIST_URL = ""
ALIST_TOKEN = ""
ALIST_PATH = "/telegram"
WEBDAV_URL = ""
WEBDAV_USER = ""
WEBDAV_PASS = ""
WEBDAV_PATH = "/telegram"

# KV 命名空间配置
[[kv_namespaces]]
binding = "CHANNEL_STORE"
id = ""

# 开发环境配置
[env.dev]
vars = { BOT_TOKEN = "DEV_BOT_TOKEN", ALIST_URL = "https://dev-alist-instance.com", ALIST_TOKEN = "dev-alist-token" }
kv_namespaces = [
  { binding = "CHANNEL_STORE", id = "dev-kv-namespace-id" }
]

# 生产环境配置
[env.production]
vars = { BOT_TOKEN = "", ALIST_URL = "", ALIST_TOKEN = "" }
kv_namespaces = [
  { binding = "CHANNEL_STORE", id = "" }
]